# Generated by Django 3.2.11 on 2022-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_telefon_email_mekan_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sosial_Şəbəkələr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.TextField(max_length=50000)),
                ('youtube', models.TextField(max_length=50000)),
                ('instagram', models.TextField(max_length=50000)),
            ],
        ),
    ]
