# Generated by Django 3.2.11 on 2022-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xidmətlər',
            name='dahaetrafli_foto',
            field=models.ImageField(default=' ', upload_to='825x400'),
            preserve_default=False,
        ),
    ]
