# Generated by Django 3.2.11 on 2022-01-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSəhifə_QəbulaYazıl_Mətnləri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('basliq', models.TextField(max_length=50000)),
                ('metn', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metn', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Giriş_Hissə',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('basliq', models.TextField(max_length=50000)),
                ('metn', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Haqqımda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('yanfoto', models.ImageField(upload_to='media/')),
                ('basliq', models.TextField(max_length=50000)),
                ('metn', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Loqo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loqo', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='MüştəriRəyləri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('metn', models.TextField(max_length=50000)),
                ('instagram', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='MüştəriRəyləri_ÜstMətn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.TextField(max_length=50000)),
                ('metn', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='SaytinBaşlığıİcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='SaytınBaşlığı',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Tez_Tez_VerilənSuallar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('sual_1', models.TextField(max_length=50000)),
                ('cavab_1', models.TextField(max_length=50000)),
                ('sual_2', models.TextField(max_length=50000)),
                ('cavab_2', models.TextField(max_length=50000)),
                ('sual_3', models.TextField(max_length=50000)),
                ('cavab_3', models.TextField(max_length=50000)),
                ('sual_4', models.TextField(max_length=50000)),
                ('cavab_4', models.TextField(max_length=50000)),
                ('sual_5', models.TextField(max_length=50000)),
                ('cavab_5', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Tez_Tez_VerilənSuallarÜstMətn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.TextField(max_length=50000)),
                ('kicik_metn', models.TextField(max_length=50000)),
            ],
        ),
    ]
