# Generated by Django 3.2.11 on 2022-03-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20220314_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil_HaqqımızdaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
