# Generated by Django 3.2.11 on 2022-03-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_mobil_haqqımızdafoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobil_HaqqımızdaFoto',
        ),
    ]
