# Generated by Django 3.2.11 on 2022-02-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaqqımızdaÜçSektoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_1', models.ImageField(upload_to='media/')),
                ('foto_2', models.ImageField(upload_to='media/')),
                ('foto_3', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
